##### Trainer #####
trainer:
  accelerator: gpu                                         
  devices: 1                                              
  max_epochs: 300
  precision: 16
  check_val_every_n_epoch: 1
  gradient_clip_val: 3

##### Data Module ######
datamodule:
  batch_size: 64
  shuffle: true
  num_workers: 10
  pin_memory: true
  drop_last: true
  persistent_workers: true

###### Linear Classifier ######
model:
  num_classes: 10                             # for STL10 is 10
  n_last_blocks: 4                            # only for ViTs: number of last attention blocks to consider
  avgpool: false                              # only for ViTs: if avgpool output from attentions
  freeze: false                               # if True, backbone weights are frozen.

##### Callbacks #####
callbacks:
  filename: epoch={epoch}-step={step}-val_loss={loss/val:.3f}-val_acc={acc/val:.3f}
  monitor: acc/val
  mode: max
  save_top_k: 10
  patience: 20